version: '3'

volumes:
  msdb_local_postgres_data: {}
  msdb_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: msdb_local_django
    container_name: msdb_local_django
    depends_on:
      - cloudsql-proxy
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.secrets/.postgres
    ports:
      - '8000:8000'
    command: /start

  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:latest
      command: /cloud_sql_proxy -instances=msdb-sep6:europe-west3:msdb-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json 
      ports:
        - 5432:5432
      volumes:
        - ./msdb-sep6-d95734a89f97.json:/secrets/cloudsql/credentials.json
      restart: always

