version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: msdb_production_django
    volumes:
      - production_django_media:/app/msdb/media
    depends_on:
      - cloudsql-proxy
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.secrets/.env
    command: /start

  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:latest
      command: /cloud_sql_proxy -instances=msdb-sep6:europe-west3:msdb-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json 
      ports:
        - 5432:5432
      volumes:
        - ./msdb-sep6-d95734a89f97.json:/secrets/cloudsql/credentials.json
      restart: always

  # traefik:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/traefik/Dockerfile
  #   image: msdb_production_traefik
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_traefik:/etc/traefik/acme
  #   ports:
  #     - '0.0.0.0:80:80'
  #     - '0.0.0.0:443:443'

  redis:
    image: redis:6

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: msdb_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
