version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: msdb_production_django
    depends_on:
      - cloudsql-proxy
    ports:
      - '8000:8000'
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.secrets/.omdbapi
    command: /start

  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:latest
      command: /cloud_sql_proxy -instances=msdb-sep6:europe-west3:msdb-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 5432:5432
      volumes:
        - ./msdb-sep6-d95734a89f97.json:/secrets/cloudsql/credentials.json
      restart: always
