# Generated by Django 4.1.9 on 2023-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
            ],
        ),
    ]
