# Generated by Django 4.2.1 on 2023-05-21 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msdb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="text",
        ),
    ]
